kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
  annotations:
    link.argocd.argoproj.io/external-link: https://hub.docker.com/repository/docker/clouduserlo$
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
       —name: nginx-app
          image: nginx
          ports:
           —containerPort: 80
