# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx-app
# #  annotations:
# #    link.argocd.argoproj.io/external-link: https://hub.docker.com/repository/docker/clouduserlo$
# spec:
#   selector:
#     matchLabels:
#       app: nginx-app
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app: nginx-app
#     spec:
#       containers:
#        —name: nginx-app
#           image: nginx
#           ports:
#            —containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    apps: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
           
